#!/usr/bin/env bash

EXECUTABLE=/opt/conda/bin/iruby

if [ ! -e "$EXECUTABLE" ]; then
    echo "Installing iruby ..."
    # epl-release should be already installed via dockerfile
    sudo yum install -y epel-release
    sudo yum install -y czmq-devel
    # make and ruby should be already conda installed via dockerfile
    conda install -y gxx_linux-64 
    gem install cztop iruby
    # shouldn't need to register iruby because of custom script
fi

## what does this do?
# hash -r
if [ ! -e "$EXECUTABLE" ]; then
  echo "Installation failed!"
  exit 2
fi

exec $EXECUTABLE "$@"
